# Generated by Django 4.1.7 on 2023-05-29 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studio45_code', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('query_user_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('discussion_type', models.CharField(choices=[('Poem', 'Poem'), ('Post', 'Post'), ('Both', 'Both')], default='', max_length=255)),
                ('view_only', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Followers', 'Followers'), ('School/gym', 'School/gym')], default='', max_length=255)),
                ('thought', models.TextField(blank=True, null=True)),
                ('martial_art_style', models.CharField(blank=True, max_length=120, null=True)),
                ('word', models.CharField(blank=True, default='', max_length=100000, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('hide_user_post', models.ManyToManyField(blank=True, related_name='hide_post_user', to=settings.AUTH_USER_MODEL)),
                ('report_times', models.ManyToManyField(blank=True, related_name='report_post_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to=settings.AUTH_USER_MODEL)),
                ('vote', models.ManyToManyField(blank=True, related_name='vote_post_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('notification', models.CharField(blank=True, max_length=255, null=True)),
                ('is_seen', models.BooleanField(blank=True, default=False, null=True)),
                ('notification_type', models.CharField(choices=[('Post', 'Post')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='affiliation_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('department_division', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('organization_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('purpose_of_affiliation', models.TextField()),
                ('affiliation_agreement', models.BooleanField(blank=True, max_length=100, null=True)),
                ('schoolgym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studio45_code.schoolgym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_section', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Martial_Arts_Type', models.CharField(max_length=255)),
                ('Number_of_Years_practiced', models.IntegerField()),
                ('Rank', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
