# Generated by Django 4.1.4 on 2023-01-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio45_code', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
