# Generated by Django 4.1.4 on 2023-01-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio45_code', '0003_alter_pages_created_at_alter_pages_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='contant',
            field=models.TextField(),
        ),
    ]
