# Generated by Django 4.1.4 on 2023-01-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio45_code', '0005_alter_pages_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
