# Generated by Django 4.1.4 on 2023-01-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio45_code', '0006_alter_pages_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='location',
        ),
    ]
