# Generated by Django 4.1.4 on 2023-01-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio45_code', '0007_remove_events_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
