# Generated by Django 4.1.4 on 2023-01-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio45_code', '0008_alter_events_address_alter_events_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminarinformation',
            name='dates_of_seminar',
        ),
        migrations.AddField(
            model_name='seminarinformation',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='seminarinformation',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='seminarinformation',
            name='why_is_this_seminar_only_open_to_this_group_of_people',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
