# Generated by Django 4.1.4 on 2023-01-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio45_code', '0009_remove_seminarinformation_dates_of_seminar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
