# Generated by Django 4.1.4 on 2023-01-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio45_code', '0010_alter_events_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarinformation',
            name='does_this_event_accept_foreign_participants',
            field=models.BooleanField(default=False),
        ),
    ]
