# Generated by Django 4.1.4 on 2023-01-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio45_code', '0011_alter_seminarinformation_does_this_event_accept_foreign_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Event_images/'),
        ),
    ]
