# Generated by Django 4.1.4 on 2023-01-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio45_code', '0012_alter_events_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image_update',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_images/'),
        ),
    ]
