# Generated by Django 4.1.4 on 2023-01-13 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio45_code', '0014_seminarinformation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminarinformation',
            name='image',
        ),
    ]
