# Generated by Django 4.1.4 on 2023-01-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio45_code', '0015_remove_seminarinformation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolgym',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='schoolym_images/'),
        ),
        migrations.AddField(
            model_name='seminarinformation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Seminar_images/'),
        ),
    ]
