# Generated by Django 4.1.4 on 2023-01-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio45_code', '0024_alter_events_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Industry', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
