# Generated by Django 4.1.4 on 2023-01-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio45_code', '0025_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='newfile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
