# Generated by Django 4.1.4 on 2022-12-20 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract_app', '0004_alter_contract_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_billing', to='contract_app.contract'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_companies', to='contract_app.contract'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_status',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_persons', to='contract_app.contract'),
        ),
        migrations.AlterField(
            model_name='product',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_products', to='contract_app.contract'),
        ),
    ]
